server:
  port: 8080
spring:
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
  datasource:
    url: jdbc:h2:mem:paymentsdb
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
